name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ] # main 브랜치에 푸시될 때 실행

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 유니티 빌드 파일이 들어있는 실제 경로 (예: docs 폴더)
          path: './docs'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Node.js 24 강제 설정 (경고 해결)